name: Syntax Check

on:
  push:
    branches:
      - main
      - python_oop
      - python-basics
      - python_typing


jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run syntax check
      run: ./run_syntax_check.sh